// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEYftIxnGXBUk1HNDhhUgQcn9W-rg9g3c',
    appId: '1:146134910822:web:185135ce7188b9a1feeaa7',
    messagingSenderId: '146134910822',
    projectId: 'finalproject-8ca94',
    authDomain: 'finalproject-8ca94.firebaseapp.com',
    storageBucket: 'finalproject-8ca94.firebasestorage.app',
    measurementId: 'G-H33E1P70NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEU0ciIF05xby2Yd2ZoxR8KUCBlPuWE1k',
    appId: '1:146134910822:android:3b81fd36f3a948c5feeaa7',
    messagingSenderId: '146134910822',
    projectId: 'finalproject-8ca94',
    storageBucket: 'finalproject-8ca94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4KFH2wHWiJt16sP8YubZJXFw9K0Vt96I',
    appId: '1:146134910822:ios:2c56d459c88cf7e3feeaa7',
    messagingSenderId: '146134910822',
    projectId: 'finalproject-8ca94',
    storageBucket: 'finalproject-8ca94.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4KFH2wHWiJt16sP8YubZJXFw9K0Vt96I',
    appId: '1:146134910822:ios:2c56d459c88cf7e3feeaa7',
    messagingSenderId: '146134910822',
    projectId: 'finalproject-8ca94',
    storageBucket: 'finalproject-8ca94.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEYftIxnGXBUk1HNDhhUgQcn9W-rg9g3c',
    appId: '1:146134910822:web:8be99c6ec9fdfdbefeeaa7',
    messagingSenderId: '146134910822',
    projectId: 'finalproject-8ca94',
    authDomain: 'finalproject-8ca94.firebaseapp.com',
    storageBucket: 'finalproject-8ca94.firebasestorage.app',
    measurementId: 'G-WFM5N1HJKD',
  );
}
